### ISSUE TITLE
Token retrieval from file not working

### ISSUE THREAD

**Issue by philicious** [hazelcast/hazelcast-kubernetes#42]
when trying to use the REST API method, it fails to read the token from file, however also doesnt throw an exception that reading fails. 

all you see is a null for the token
```
INFO: [10.4.1.222]:5701 [dev] [3.7.4] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-label: vertx-cluster, service-label-value: true, namespace: production, kubernetes-master: https://kubernetes.default.svc}
Sep 06, 2017 1:44:03 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.4.1.222]:5701 [dev] [3.7.4] Kubernetes Discovery: Bearer Token { null }
```
and later 
```
SEVERE: [10.4.1.222]:5701 [dev] [3.7.4] null
java.lang.NullPointerException
    at com.hazelcast.kubernetes.ServiceEndpointResolver.getSimpleDiscoveryNodes(ServiceEndpointResolver.java:115)
    at com.hazelcast.kubernetes.ServiceEndpointResolver.getDiscoveryNodes(ServiceEndpointResolver.java:105)
    at com.hazelcast.kubernetes.ServiceEndpointResolver.resolve(ServiceEndpointResolver.java:84)
    at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:98)
```

if you specify the token via property `api-token` , its all working fine

PS: DNS method didnt work at all but no errors

**Comment by mrahbar** [comment]
I observed the same logs. The scenario is that getAccountToken() returns null, leading to that log message but the fabric8 kubernetes client reads the token again from the well knon path /var/run/secrets/kubernetes.io/serviceaccount/token

You can check if the NPE maybe is actually from this line 
https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java#L116
where getAddresses() is null because there are no ready endpoints. This is my issue currently.

Btw. the api-token property was from my PR

**Comment by avalcepina** [comment]
I'm having the same issue. Did it turn out to be the getAddresses method or was it really the getSubsets? Also did you ever manage to solve it somehow?

**Comment by philicious** [comment]
I never solved the problem with reading the api-token file as its working fine with the api-token property and that was sufficient at that point. thx @mrahbar !

**Comment by googlielmo** [comment]
Cannot reproduce, closing this.

**Comment by philicious** [comment]
@googlielmo I'm not sure simply closing this is the right approach. there are at least two people having this problem

**Comment by googlielmo** [comment]
@philicious @avalcepina : do you have a chance to check again with the latest master?
The NPE mentioned by @mrahbar was just fixed with #52, and #51 upgraded the fabric8 client version.
Happy to reopen this if the issue is still there. And if it is, to fix it!

**Comment by philicious** [comment]
@googlielmo I'm not sure I can do as I'm only 16 more days at that project and there are other things they need me to do :/

**Comment by googlielmo** [comment]
No problem at all @philicious, if you could provide the following info I would try again to reproduce it myself:
- hazelcast-kubernetes plugin version
- hazelcast-kubernetes plugin configuration properties
- hazelcast version
- kubernetes version

Cheers, Guglielmo

**Comment by avalcepina** [comment]
Maybe I can help. I managed to find out what the problem was in my case and solve it. 
The issue was that the when discovering the hazelcast service in kubernetes we were trying to match by name and label. Since the service wasn't ready yet, though, both these attempt were returning an empty list. When that happened a third attempt was made using only the namespace. Some of the services in the namespaces were returning an null subset (not sure why) and causing a nullpointer exception. 
I solved the issue momentarily by deploying a custom version of the library that allows to specify whether the namespace lookup should take place or not and also has a null check on the subset. I was planning on creating a pull request for it (although I think something along those lines already exists), maybe I can find some time today. I'm not sure, however, this is the same issue @philicious is having.

**Comment by googlielmo** [comment]
Hi @avalcepina, thanks for the feedback!

The issue you describe looks indeed the same as #43 , which was solved by #52.
Would you please verify it's the same null subsets that you came upon?

Btw, the logic of lookup has been smoothed out with #30, so now it doesn't fall back on the namespace lookup if the user specifies a label.

**Comment by avalcepina** [comment]
Hi,
#52 does not solve the issue actually. I was getting the nullpointer on  endpoints.getSubsets(), so before getting to getAddresses.

**Comment by philicious** [comment]
@googlielmo 

version: 'com.hazelcast:hazelcast-kubernetes:1.0.0',

config
```
            <discovery-strategies>
                <discovery-strategy enabled="true"
                                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">

                    <properties>
                        <!-- configure discovery service API lookup -->
                        <property name="service-label-name">vertx-cluster</property>
                        <property name="service-label-value">true</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
```
k8s version is 1.7.x

**Comment by googlielmo** [comment]
Interesting @avalcepina, though it looks like it's unrelated to the original issue of token retrieval.
I will open a new issue for getSubsets() returning null, which we currently don't check!
Thanks.

**Comment by googlielmo** [comment]
Thanks @philicious for the info, I will try to reproduce the original issue.
